spring:
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
  datasource:
    url: jdbc:mariadb://planet.csndvegemmbq.ap-northeast-2.rds.amazonaws.com:3306/Planet
    username: admin
    password: zhemzmfflr12
    driver-class-name: org.mariadb.jdbc.Driver

    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 30
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

mybatis:
  type-aliases-package: com.groupware.planet.vo
  mapper-locations: sqlmap/**/*.xml

logging:
  level:
    jdbc:
      sqlonly: debug
      sqltiming: off
      audit: info
      resultset: off
      resultsettable: debug
    org.springframework.web: info
    com.zaxxer.hikari.HikariDataSource: info

server:
  error:
    include-exception: false
    include-stacktrace: never
    path: '/error'
    whitelabel:
      enabled: true
  port: 8080